apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webapp.fullname" . }}-html
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
data:
  index.html: |
    <html>
      <body>
        <h1>{{ .Values.html.message | default "Hello from the Helm workshop!" }}</h1>
      </body>
    </html>
