apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: webapp
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
