apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-greeter
data:
  greeting: {{ .Values.message | quote }}
  environment: {{ .Values.global.environment | default "unspecified" | quote }}
